### ISSUE TITLE
GPU Numbers consistent with claymore/Afterburner

### ISSUE THREAD

**Issue by RyanLucchese** [energicryptocurrency/energiminer#45] opened 2018-04-23 21:47 UTC
Claymore miner supports GPU number labels which are consistent with the numbers reported by MSI Afterburner. We should support this as well.

**Comment by RyanLucchese** [comment] 2018-04-23 21:48
![](https://github.trello.services/images/mini-trello-icon.png) [energiminer: GPU Numbers consistent with claymore/Afterburner](https://trello.com/c/93tYDaZX/162-energiminer-gpu-numbers-consistent-with-claymore-afterburner)

**Comment by andvgal** [comment] 2018-11-12 17:54
Closing as duplicate of internal backlog.

**Closed by andvgal** 2018-11-12 17:54 UTC
Labels: Feature, User Affected
